# Generated by Django 6.0.7 on 2026-07-15 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarineProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdpa_pid', models.BigIntegerField(db_index=True, unique=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('protected_area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('designation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('iucn_category', models.CharField(blank=True, max_length=50, null=True)),
                ('realm', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('reported_area', models.FloatField(blank=True, null=True)),
                ('gis_area', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('governance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('management_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Marine Protected Area',
                'verbose_name_plural': 'Marine Protected Areas',
                'ordering': ['country_code', 'protected_area_name', 'wdpa_pid'],
            },
        ),
    ]
