# Generated by Django 6.0.7 on 2026-07-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('population', models.FloatField()),
                ('gdp_per_capita', models.FloatField()),
                ('forest_area', models.FloatField()),
                ('renewable_energy', models.FloatField()),
                ('pm25', models.FloatField()),
                ('average_temperature', models.FloatField()),
                ('co2_emissions', models.FloatField()),
            ],
            options={
                'ordering': ['country', 'year'],
                'unique_together': {('country', 'year')},
            },
        ),
    ]
