# Generated by Django 6.0.7 on 2026-08-10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0004_add_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="marineprotectedarea",
            index=models.Index(fields=["iucn_category"], name="env_mpa_iucn_idx"),
        ),
    ]