# Generated by Django 6.0.7 on 2026-08-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_add_iucn_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('country', models.CharField(max_length=150)),
                ('record_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Country Summary',
                'verbose_name_plural': 'Country Summaries',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('total_records', models.BigIntegerField(default=0)),
                ('total_countries', models.BigIntegerField(default=0)),
                ('total_designations', models.BigIntegerField(default=0)),
                ('total_realms', models.BigIntegerField(default=0)),
                ('total_governance_types', models.BigIntegerField(default=0)),
                ('total_iucn_categories', models.BigIntegerField(default=0)),
                ('latest_year', models.IntegerField(blank=True, null=True)),
                ('earliest_year', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Summary',
                'verbose_name_plural': 'Dashboard Summaries',
            },
        ),
        migrations.CreateModel(
            name='DesignationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_index=True, max_length=255, unique=True)),
                ('record_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Designation Summary',
                'verbose_name_plural': 'Designation Summaries',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governance_type', models.CharField(db_index=True, max_length=100, unique=True)),
                ('record_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Governance Summary',
                'verbose_name_plural': 'Governance Summaries',
                'ordering': ['governance_type'],
            },
        ),
        migrations.CreateModel(
            name='IUCNSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iucn_category', models.CharField(db_index=True, max_length=50, unique=True)),
                ('record_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'IUCN Summary',
                'verbose_name_plural': 'IUCN Summaries',
                'ordering': ['iucn_category'],
            },
        ),
        migrations.CreateModel(
            name='RealmSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(db_index=True, max_length=100, unique=True)),
                ('record_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Realm Summary',
                'verbose_name_plural': 'Realm Summaries',
                'ordering': ['realm'],
            },
        ),
        migrations.CreateModel(
            name='StatusSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=100, unique=True)),
                ('record_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Status Summary',
                'verbose_name_plural': 'Status Summaries',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='YearSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('record_count', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Year Summary',
                'verbose_name_plural': 'Year Summaries',
                'ordering': ['year'],
            },
        ),
        migrations.RemoveIndex(
            model_name='marineprotectedarea',
            name='env_mpa_gov_idx',
        ),
        migrations.RemoveIndex(
            model_name='marineprotectedarea',
            name='env_mpa_mgmt_idx',
        ),
        migrations.RemoveIndex(
            model_name='marineprotectedarea',
            name='env_mpa_iucn_idx',
        ),
        migrations.AlterField(
            model_name='marineprotectedarea',
            name='governance_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marineprotectedarea',
            name='iucn_category',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marineprotectedarea',
            name='management_authority',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
